cc_binary(
    name = "Demo",
    srcs = ["main.cpp"],
    deps = ["@oneTBB//:tbb"],
)

cc_binary(
    name = "invoke",
    srcs = ["1_main_parallel_invoke.cpp"],
    deps = ["@oneTBB//:tbb"],
)

cc_binary(
    name = "for",
    srcs = ["2_main_parallel_for.cpp"],
    deps = ["@oneTBB//:tbb"],
)

cc_binary(
    name = "reduce",
    srcs = ["4_main_parallel_reduce.cpp"],
    deps = ["@oneTBB//:tbb"],
)

cc_binary(
    name = "scan1",
    srcs = ["7_main_parallel_scan1.cpp"],
    deps = ["@oneTBB//:tbb"],
)

cc_binary(
    name = "scan2",
    srcs = ["8_main_parallel_scan2.cpp"],
    deps = ["@oneTBB//:tbb"],
)


